[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

dependencies = [
    "triton>=3.2.0",
    "termcolor",
]

[project]
name = "triton_runner"
version = "0.1.9"
description = "Triton multi-level runner, include cubin, ptx, ttgir etc."
authors = [
    { name = "Bob Huang", email = "git@bobhuang.xyz" },
]
license = "MIT" 

[project.urls]
repository = "https://github.com/OpenMLIR/triton_runner"
homepage = "https://triton-runner.org"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["triton_runner*"]
